services:
  php:
    image: dunglas/frankenphp:latest
    environment:
      - SERVER_NAME=:80
    restart: unless-stopped
    ports:
      - "80/tcp"
      - "443/tcp"
    volumes:
      - ./symfony:/app
    networks:
      - symfony-traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(`${PHP_HOST:-php.localhost}`)"
      - "traefik.http.routers.php.tls=true"
